version: 0.2

phases:
  build:
    commands:
       - pip3 install --upgrade awscli
       - aws --version
       - aws sts get-caller-identity
       - aws s3 ls
       - aws imagebuilder start-image-pipeline-execution --image-pipeline-arn arn:aws:imagebuilder:us-east-2:338054916879:image-pipeline/webamimaker --region us-east-2

