version: 0.2

phases:
  build:
    commands:
       - pip3 install --upgrade awscli
       - aws --version
       - aws sts get-caller-identity
       - aws s3 ls
       - pip3 install boto3
       - python3 python.py
