version: 0.2

phases:
  build:
    commands:
       - pip3 install --upgrade awscli
       - aws --version
       - aws sts get-caller-identity
       - aws s3 ls
       - arn=`aws cloudformation describe-stacks --stack-name revelmediagroup-dev-image-pipeline --query "Stacks[0].Outputs[0].OutputValue" --output text --region us-east-1`
       - aws imagebuilder start-image-pipeline-execution --image-pipeline-arn $arn --region us-east-1
       - python python.py
